### ISSUE TITLE
NullReferenceException on building

### ISSUE THREAD

**Issue by dittodhole** [distantcam/ConfigureAwait#3]
> 2>    Fody (version 1.28.3.0) Executing
2>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Object reference not set to an instance of an object.
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    at Mono.Cecil.ImportGenericContext.TypeParameter(String type, Int32 position)
2>MSBUILD : error :    at Mono.Cecil.MetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
2>MSBUILD : error :    at Mono.Cecil.MetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
2>MSBUILD : error :    at Mono.Cecil.MetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
2>MSBUILD : error :    at Mono.Cecil.MetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
2>MSBUILD : error :    at Mono.Cecil.MetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
2>MSBUILD : error :    at Mono.Cecil.MetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
2>MSBUILD : error :    at Mono.Cecil.ModuleDefinition.Import(TypeReference type)
2>MSBUILD : error :    at ConfigureAwait.ModuleWeaver.AddAwaitConfigToAsyncMethod(TypeDefinition type, Boolean value) in C:\projects\configureawait\src\ConfigureAwait\ModuleWeaver.cs:line 95
2>MSBUILD : error :    at ConfigureAwait.ModuleWeaver.ProcessType(Nullable`1 assemblyConfigureAwaitValue, TypeDefinition type) in C:\projects\configureawait\src\ConfigureAwait\ModuleWeaver.cs:line 69
2>MSBUILD : error :    at ConfigureAwait.ModuleWeaver.Execute() in C:\projects\configureawait\src\ConfigureAwait\ModuleWeaver.cs:line 41
2>MSBUILD : error :    at lambda_method(Closure , Object )
2>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 144
2>MSBUILD : error :    at InnerWeaver.Execute() in c:\ConsoleBuildAgent\work\ed448661dbb30d2e\FodyIsolated\InnerWeaver.cs:line 62
2>MSBUILD : error : Source:
2>MSBUILD : error : Mono.Cecil
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Mono.Cecil.TypeReference TypeParameter(System.String, Int32)
2>MSBUILD : error : 
2>      Finished Fody 100ms.

**Comment by mtumashenko** [comment]
Got similar exception:

Severity	Code	Description	Project	File	Line
Error		Fody: An unhandled exception occurred:
Exception:
Object reference not set to an instance of an object.
StackTrace:
   at Mono.Cecil.ImportGenericContext.TypeParameter(String type, Int32 position)
   at Mono.Cecil.MetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportTypeSpecification(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportType(TypeReference type, ImportGenericContext context)
   at Mono.Cecil.MetadataImporter.ImportReference(TypeReference type, IGenericParameterProvider context)
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type, IGenericParameterProvider context)
   at Mono.Cecil.ModuleDefinition.ImportReference(TypeReference type)
   at ConfigureAwait.ModuleWeaver.AddAwaitConfigToAsyncMethod(TypeDefinition type, Boolean value) in C:\projects\configureawait\src\ConfigureAwait\ModuleWeaver.cs:line 93
   at ConfigureAwait.ModuleWeaver.ProcessType(Nullable`1 assemblyConfigureAwaitValue, TypeDefinition type) in C:\projects\configureawait\src\ConfigureAwait\ModuleWeaver.cs:line 69
   at ConfigureAwait.ModuleWeaver.Execute() in C:\projects\configureawait\src\ConfigureAwait\ModuleWeaver.cs:line 41
   at lambda_method(Closure , Object )
   at InnerWeaver.ExecuteWeavers() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 164
   at InnerWeaver.Execute() in c:\Code\Fody\FodyIsolated\InnerWeaver.cs:line 82
Source:
Mono.Cecil
TargetSite:
Mono.Cecil.TypeReference TypeParameter(System.String, Int32)

**Comment by caesay** [comment]
I'm getting the same error. There's been no feedback on the original issue, so i doubt this project is maintained anymore, but bump anyways.

**Comment by distantcam** [comment]
Should be fixed in 0.3.0
